-- properties: 6 rows
DELETE FROM properties;
INSERT INTO properties (id, property_name, slug, property_type, area_name, address, price, bhk, sq_ft, description, amenities, latitude, longitude, status, is_featured, listing_type, view_count, primary_image, owner_admin_id, creation_source, block_wing, unit_number, listing_intent, seller_type, created_at, updated_at) VALUES (1, 'Premium 3BHK Flat - Vesu', 'premium-3bhk-flat-vesu', 'flat', 'Vesu', 'Vesu Main Road, Surat', 8500000.0, 3, 1450.0, 'Spacious 3BHK with modular kitchen and covered parking near VR Mall.', '["parking", "lift", "security", "gym"]'::jsonb, 21.1415, 72.7758, 'available', TRUE, 'sale', 0, NULL, NULL, 'admin', NULL, NULL, 'sell', NULL, '2026-08-29T06:06:05+00:00', '2026-08-29T06:06:05+00:00');
INSERT INTO properties (id, property_name, slug, property_type, area_name, address, price, bhk, sq_ft, description, amenities, latitude, longitude, status, is_featured, listing_type, view_count, primary_image, owner_admin_id, creation_source, block_wing, unit_number, listing_intent, seller_type, created_at, updated_at) VALUES (2, 'Commercial Shop - Adajan', 'commercial-shop-adajan', 'shop', 'Adajan', 'Adajan Patiya, Surat', 4500000.0, 0, 450.0, 'Prime commercial shop on main road with high footfall.', '["parking", "power_backup"]'::jsonb, 21.1956, 72.7934, 'available', TRUE, 'sale', 0, NULL, NULL, 'admin', NULL, NULL, 'sell', NULL, '2026-08-29T06:06:05+00:00', '2026-08-29T06:06:05+00:00');
INSERT INTO properties (id, property_name, slug, property_type, area_name, address, price, bhk, sq_ft, description, amenities, latitude, longitude, status, is_featured, listing_type, view_count, primary_image, owner_admin_id, creation_source, block_wing, unit_number, listing_intent, seller_type, created_at, updated_at) VALUES (3, 'Office Space - Piplod', 'office-space-piplod', 'office', 'Piplod', 'Piplod, Surat', 120000.0, 0, 1200.0, 'Furnished office in commercial complex.', '["lift", "security", "cafeteria"]'::jsonb, 21.1608, 72.7712, 'available', FALSE, 'sale', 0, NULL, NULL, 'admin', NULL, NULL, 'sell', NULL, '2026-08-29T06:06:05+00:00', '2026-08-29T06:06:05+00:00');
INSERT INTO properties (id, property_name, slug, property_type, area_name, address, price, bhk, sq_ft, description, amenities, latitude, longitude, status, is_featured, listing_type, view_count, primary_image, owner_admin_id, creation_source, block_wing, unit_number, listing_intent, seller_type, created_at, updated_at) VALUES (4, 'Luxury Bungalow - Dumas', 'luxury-bungalow-dumas', 'bungalow', 'Dumas', 'Dumas Road, Surat', 25000000.0, 4, 3500.0, '4BHK bungalow with garden and private terrace.', '["garden", "parking", "security"]'::jsonb, 21.0892, 72.8145, 'available', TRUE, 'sale', 0, NULL, NULL, 'admin', NULL, NULL, 'sell', NULL, '2026-08-29T06:06:05+00:00', '2026-08-29T06:06:05+00:00');
INSERT INTO properties (id, property_name, slug, property_type, area_name, address, price, bhk, sq_ft, description, amenities, latitude, longitude, status, is_featured, listing_type, view_count, primary_image, owner_admin_id, creation_source, block_wing, unit_number, listing_intent, seller_type, created_at, updated_at) VALUES (5, 'Residential Plot - Pal', 'residential-plot-pal', 'plot', 'Pal', 'Pal Area, Surat', 3200000.0, 0, 1800.0, 'Clear title plot in developing area.', '["gated", "water", "electricity"]'::jsonb, 21.2053, 72.8987, 'available', FALSE, 'sale', 0, NULL, NULL, 'admin', NULL, NULL, 'sell', NULL, '2026-08-29T06:06:05+00:00', '2026-08-29T06:06:05+00:00');
INSERT INTO properties (id, property_name, slug, property_type, area_name, address, price, bhk, sq_ft, description, amenities, latitude, longitude, status, is_featured, listing_type, view_count, primary_image, owner_admin_id, creation_source, block_wing, unit_number, listing_intent, seller_type, created_at, updated_at) VALUES (6, '2BHK Flat - Varachha', '2bhk-flat-varachha', 'flat', 'Varachha', 'Varachha Road, Surat', 4200000.0, 2, 980.0, 'Affordable 2BHK near ring road.', '["lift", "security"]'::jsonb, 21.2315, 72.8543, 'available', FALSE, 'sale', 0, NULL, NULL, 'admin', NULL, NULL, 'sell', NULL, '2026-08-29T06:06:05+00:00', '2026-08-29T06:06:05+00:00');
SELECT setval(pg_get_serial_sequence('properties', 'id'), COALESCE((SELECT MAX(id) FROM properties), 1));
